<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PayFlow.Webhooks.Domain\PayFlow.Webhooks.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayFlow.EventBus.Abstractions\PayFlow.EventBus.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PayFlow.Webhooks.UnitTests" />
    <InternalsVisibleTo Include="PayFlow.Webhooks.IntegrationTests" />
  </ItemGroup>

</Project>
