<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PayFlow.Reporting.Domain\PayFlow.Reporting.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayFlow.EventBus.Abstractions\PayFlow.EventBus.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PayFlow.Reporting.UnitTests" />
  </ItemGroup>

</Project>
