namespace PayFlow.Identity.API.Endpoints;

/// <summary>
/// Maps Application/Domain error codes to RFC 7807 responses.
///
/// Every field-related code — whether shape-invalid (422) or in conflict
/// with existing state (409) — surfaces as ValidationProblemDetails:
///     errors: { FieldName: [STABLE_CODE] }
/// The status code carries the semantic (validation vs conflict); the body
/// shape stays constant so clients always parse the same structure.
///
/// Codes the public path is not supposed to produce (defensive internal
/// guards) fall through to a 500 with the code as a top-level extension.
/// </summary>
internal static class ErrorMapping
{
    private static readonly Dictionary<string, (string Field, int Status)> Codes =
        new(StringComparer.Ordinal)
        {
            // Shape / format invalid → 422
            ["EMAIL_REQUIRED"] = ("AdminEmail", StatusCodes.Status422UnprocessableEntity),
            ["EMAIL_INVALID"] = ("AdminEmail", StatusCodes.Status422UnprocessableEntity),
            ["TENANT_NAME_REQUIRED"] = ("Name", StatusCodes.Status422UnprocessableEntity),
            ["TENANT_SLUG_REQUIRED"] = ("Slug", StatusCodes.Status422UnprocessableEntity),
            ["TENANT_SLUG_INVALID"] = ("Slug", StatusCodes.Status422UnprocessableEntity),
            ["DISPLAY_NAME_REQUIRED"] = ("AdminDisplayName", StatusCodes.Status422UnprocessableEntity),

            // State conflict → 409 (still field-keyed)
            ["TENANT_SLUG_TAKEN"] = ("Slug", StatusCodes.Status409Conflict),
        };

    public static IResult ToProblem(string errorCode)
    {
        if (Codes.TryGetValue(errorCode, out var entry))
        {
            return Results.ValidationProblem(
                new Dictionary<string, string[]>
                {
                    [entry.Field] = [errorCode],
                },
                statusCode: entry.Status,
                title: TitleFor(entry.Status));
        }

        // Non-field-related errors get the regular Problem shape.
        return errorCode switch
        {
            "AUTH_INVALID_CREDENTIALS" => Results.Problem(
                statusCode: StatusCodes.Status401Unauthorized,
                title: "Invalid credentials",
                detail: "The tenant slug, email, or password is not correct.",
                extensions: new Dictionary<string, object?> { ["code"] = errorCode }),

            // PASSWORD_HASH_REQUIRED, TENANT_REQUIRED — defensive internal
            // guards. FluentValidation catches blanks earlier, and tenant id
            // is generated by the aggregate factory. If we ever see one, it
            // is a programmer mistake worth a 500.
            _ => Results.Problem(
                statusCode: StatusCodes.Status500InternalServerError,
                title: "Unexpected error",
                detail: $"Unmapped or internal error code '{errorCode}'.",
                extensions: new Dictionary<string, object?> { ["code"] = errorCode }),
        };
    }

    private static string? TitleFor(int statusCode) => statusCode switch
    {
        StatusCodes.Status409Conflict => "Resource conflict",
        _ => null, // let ValidationProblem use its default title
    };
}
