namespace PayFlow.Identity.API.Endpoints;

/// <summary>
/// Maps Application/Domain error codes to RFC 7807 ProblemDetails responses.
///
/// Codes that map to a request field surface as 422 ValidationProblem with the
/// same shape FluentValidation produces — `errors: { FieldName: [CODE, ...] }`.
/// That keeps a single response contract for clients regardless of which
/// validation layer rejected the input.
///
/// Codes without a field (conflicts, internal bugs) keep the regular Problem
/// shape with a top-level `code` extension.
/// </summary>
internal static class ErrorMapping
{
    // Domain error codes → request field name. The endpoint translates a
    // failure with one of these codes into a field-keyed ValidationProblem.
    private static readonly Dictionary<string, string> CodeToField = new(StringComparer.Ordinal)
    {
        ["EMAIL_REQUIRED"] = "AdminEmail",
        ["EMAIL_INVALID"] = "AdminEmail",
        ["TENANT_NAME_REQUIRED"] = "Name",
        ["TENANT_SLUG_REQUIRED"] = "Slug",
        ["TENANT_SLUG_INVALID"] = "Slug",
        ["DISPLAY_NAME_REQUIRED"] = "AdminDisplayName",
    };

    public static IResult ToProblem(string errorCode)
    {
        if (CodeToField.TryGetValue(errorCode, out var field))
        {
            return Results.ValidationProblem(
                new Dictionary<string, string[]>
                {
                    [field] = [errorCode],
                },
                statusCode: StatusCodes.Status422UnprocessableEntity);
        }

        return errorCode switch
        {
            "TENANT_SLUG_TAKEN" => Results.Problem(
                statusCode: StatusCodes.Status409Conflict,
                title: "Tenant slug already in use",
                detail: "The slug is taken by another tenant. Choose a different one.",
                extensions: new Dictionary<string, object?> { ["code"] = errorCode }),

            // PASSWORD_HASH_REQUIRED, TENANT_REQUIRED are defensive — the public
            // path should never produce them (FluentValidation catches blanks
            // earlier, and tenant id is generated by the aggregate factory).
            // If we ever see one, it is a programmer mistake worth a 500.
            _ => Results.Problem(
                statusCode: StatusCodes.Status500InternalServerError,
                title: "Unexpected error",
                detail: $"Unmapped or internal error code '{errorCode}'.",
                extensions: new Dictionary<string, object?> { ["code"] = errorCode }),
        };
    }
}
