<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PayFlow.Notification.Domain\PayFlow.Notification.Domain.csproj" />
    <ProjectReference Include="..\PayFlow.Notification.Application\PayFlow.Notification.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayFlow.Outbox\PayFlow.Outbox.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\PayFlow.EventBus.Kafka\PayFlow.EventBus.Kafka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PayFlow.Notification.UnitTests" />
    <InternalsVisibleTo Include="PayFlow.Notification.IntegrationTests" />
  </ItemGroup>

</Project>
