apiVersion: v1
kind: Secret
metadata:
  name: payflow-shared-secrets
  labels:
    {{- include "payflow.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  Identity__Jwt__SigningKey: {{ required "secrets.jwtSigningKey is required" .Values.secrets.jwtSigningKey | quote }}
  PG_USER: {{ required "secrets.pgUser is required" .Values.secrets.pgUser | quote }}
  PG_PASSWORD: {{ required "secrets.pgPassword is required" .Values.secrets.pgPassword | quote }}
  PG_DB: {{ required "secrets.pgDb is required" .Values.secrets.pgDb | quote }}
